In [1]:
import torch

In [6]:
a = torch.FloatTensor([[1,2,3],[4,5,6]])
b = torch.DoubleTensor([[1,2,3],[4,5,6]])
print(a.dtype)
print(b.dtype)
print(a.mean())
print(a.mean(dim=0, keepdim=True))
print(a.mean(dim=1, keepdim=True))

torch.float32
torch.float64
tensor(3.5000)
tensor([[ 2.5000,  3.5000,  4.5000]])
tensor([[ 2.],
        [ 5.]])


In [7]:
print(a.std())

tensor(1.8708)


In [8]:
print(a.std(dim=0))

tensor([ 2.1213,  2.1213,  2.1213])


In [10]:
print(a.shape)
print(a.view(3,-1))
print(a.reshape((3,-1)))

torch.Size([2, 3])
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]])
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]])


Tensor.view() works only on contiguous tensors and will never copy memory. It will raise an error on a non-contiguous tensor.
Tensor.reshape() will work on any tensor and can make a clone if it is needed.

In [11]:
c = torch.randn(2,3,4)
print(c.shape)

torch.Size([2, 3, 4])


In [13]:
print(c.squeeze().shape)

torch.Size([2, 3, 4])


In [15]:
print(c.view(-1,1).squeeze().shape)

torch.Size([24])


In [16]:
d = torch.rand(2,3)
print(d)

tensor([[ 0.0835,  0.6543,  0.2215],
        [ 0.5374,  0.3823,  0.0224]])


In [19]:
print(d.dim)

<built-in method dim of Tensor object at 0x1136e9410>


In [20]:
help(d.dim)

Help on built-in function dim:

dim(...)
    dim() -> int
    
    Returns the number of dimensions of :attr:`self` tensor.



In [21]:
d.dim()

2

In [23]:
import numpy as np
a = np.ones((2,3))
b = torch.ones((2,3))

In [24]:
print(b)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [32]:
c = torch.ones(2,3)

In [33]:
c

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [34]:
d = torch.rand_like(c,dtype=torch.float)
# create a random tensor with the same shape

In [35]:
print(d)
d[0,0]= 9
print(c)

tensor([[ 0.8827,  0.2859,  0.5821],
        [ 0.1796,  0.7386,  0.8555]])
tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [36]:
print(torch.add(d,c))
print(d)
print(c)

tensor([[ 10.0000,   1.2859,   1.5821],
        [  1.1796,   1.7386,   1.8555]])
tensor([[ 9.0000,  0.2859,  0.5821],
        [ 0.1796,  0.7386,  0.8555]])
tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [37]:
print(d.add(c))
print(d)
print(c)

tensor([[ 10.0000,   1.2859,   1.5821],
        [  1.1796,   1.7386,   1.8555]])
tensor([[ 9.0000,  0.2859,  0.5821],
        [ 0.1796,  0.7386,  0.8555]])
tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [38]:
print(d)
d.add_(c)
print(d)

tensor([[ 9.0000,  0.2859,  0.5821],
        [ 0.1796,  0.7386,  0.8555]])
tensor([[ 10.0000,   1.2859,   1.5821],
        [  1.1796,   1.7386,   1.8555]])


In [39]:
print(d.item())

ValueError: only one element tensors can be converted to Python scalars

In [40]:
print(d.sum().item())

17.6417121887


In [41]:
print(d.sum())

tensor(17.6417)


In [43]:
import torch
import csv 
CUDA = torch.cuda.is_available()
device = torch.device('cuda' if CUDA else 'cpu')
print(CUDA)
print(device.type)
print(device.index)

False
cpu
None
